development:
  adapter: postgresql
  encoding: unicode
  database: benykou_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: kitallis
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: benykou_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: kitallis
  password:
  timeout: 5000
