default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: benkyou_development

test:
  <<: *default
  database: benkyou_test

production:
  <<: *default
  database: benkyou_production
  username: kitallis
  password: <%= ENV['BENKYOU_DATABASE_PASSWORD'] %>
