name: Weather

on:
  workflow_dispatch:

jobs:  
  build:
    runs-on: tramline-macos-sonoma-md
    steps:
      - name: Install weather 📚
        run: |
          sudo apt-get update && sudo apt-get install -y ansiweather

      - name: Print the London weather 🌦
        run: |
          ansiweather -l London,GB -f 3

      - name: Write the weather to a file
        shell: bash
        run: |
          value=`ansiweather -l London,GB -f 3 > weather.txt`
          echo The result is $value
          
      - name: Upload weather file
        uses: actions/upload-artifact@v2
        with:
          name: weather
          path: weather.txt
